import { Sidebar } from "@/components/sidebar";
import { Box, Container } from "@mui/material";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Authenticated",
  description: "Generated by Dime Media LTD. ©️Copyright",
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <Box>
      <Sidebar />
      <Container
        disableGutters
        maxWidth={false}
        style={{
          backgroundColor: "white",
          width: "calc(100% - 230px)",
          height: "100vh",
          padding: "20px",
          marginLeft: 225,
        }}
      >
        {children}
      </Container>
    </Box>
  );
};

export default RootLayout;
