import type { Metadata } from "next";
import { Box } from "@mui/material";

export const metadata: Metadata = {
  title: "Authentication",
  description: "Generated by Dime Media LTD. ©️Copyright",
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return <Box sx={{ width: "100%", height: "100%" }}>{children}</Box>;
};

export default RootLayout;
