import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import { Container } from "@mui/material";

const lexend = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        <Container
          disableGutters
          maxWidth={false}
          style={{
            backgroundColor: "white",
            width: "100%",
            height: "100%",
          }}
        >
          {children}
        </Container>
      </body>
    </html>
  );
}
